### ISSUE TITLE
Add color names to color.js

### ISSUE THREAD

**Issue by bleeptrack** [bleeptrack/beetlesbot#1]
Help my beetlegenerator ([beetles.bleeptrack.de](https://beetles.bleeptrack.de) or [beetlesbot](https://twitter.com/beetlesbot) ) to generate better names by adding colors to color.js.

You will find the file under  **beetlesbot/generator/color.js**

Please add the following to the **names array**: rgb color hexcode + color name. The name should be creative and descriptive. Please keep the list sorted by hexcodes.

Thank you very much for your help!

**Comment by evwltrs** [comment]
site is down

**Comment by JackTreble** [comment]
The link above is broken, try [https://beetles.bleeptrack.de/](https://beetles.bleeptrack.de/)

**Comment by bleeptrack** [comment]
Fixed the link, sorry!

**Comment by marcosstefani** [comment]
https://github.com/bleeptrack/beetlesbot/pull/6
